# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['app_desktop_fixed.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('templates', 'templates'),
        ('static', 'static'),
        ('../backend.py', '.'),
    ],
    hiddenimports=[
        'flask',
        'werkzeug',
        'jinja2',
        'yt_dlp',
        'requests',
        'threading',
        'json',
        'os',
        'sys',
        'time',
        'datetime',
        'pathlib',
        'subprocess',
        're',
        'urllib.parse',
        'flask_cors',
        'werkzeug.middleware.proxy_fix',
        'werkzeug.serving',
        'jinja2.ext',
        'jinja2.loaders',
        'jinja2.environment',
        'jinja2.compiler',
        'jinja2.runtime',
        'jinja2.parser',
        'jinja2.lexer',
        'jinja2.utils',
        'jinja2.filters',
        'jinja2.tests',
        'jinja2.debug',
        'jinja2.optimizer',
        'jinja2.defaults',
        'jinja2.meta',
        'jinja2.visitor',
        'jinja2.exceptions',
        'jinja2.constants',
        'jinja2.nodes',
        'jinja2.idtracking',
        'jinja2.ir',
        'jinja2.codegen',
        'webview',
        'webview.platforms.winforms',
        'webview.platforms.cef',
        'webview.platforms.gtk',
        'webview.platforms.cocoa',
        'tkinter',
        'tkinter.ttk',
        'tkinter.messagebox',
        'tkinter.filedialog',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='VideoHub_Desktop_Fixed',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,  # Set to False for windowed application
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
) 